### ISSUE TITLE
Feature request: More control with faceting

### ISSUE THREAD

**Issue by billdenney** [john-harrold/ruminate#24]
I'm playing around with ruminate now.  So, you're about to see a lot of notes and feature requests.

For faceting:

1. Can you support `facet_wrap()`, `facet_grid()`, `facet_wrap_paginate()`, and `facet_grid_paginate()`?
    1. Within the `*_paginate()` functions, can you support switching between pages?
3. Can you support the `scales` argument for facetting?
4. Can you support multiple faceting variables?

**Comment by john-harrold** [comment]
Are you gaslighting me here Bill? I fell like I'm being gaslit. :)

All joking aside. There is a facet figure element. See below. If you are faceting by two variables it will use facet_grid_paginate(), and if you are faceting using 1, 3 or more variables it will use facet_wrap_paginate(). This is where the code generation is for that:

https://github.com/john-harrold/formods/blob/1ca2415593ff683894508482ff0203014f65173c/R/FG_Server.R#L2069

If there is more than one page there is a slider that will appear below the figure allowing you to select the page you want. I'm thinking about turning this into a pull down similar to multiple pages in the NCA module.  

What are you looking for with the scales?

![image](https://github.com/user-attachments/assets/721cbab7-8627-4809-97ac-84710cbc24f8)

**Comment by john-harrold** [comment]
I could put a pulldown next to the variable/column selection that has these options:

<img width="667" alt="image" src="https://github.com/user-attachments/assets/6d365783-0e13-4330-8bed-523b27f58e81">

**Comment by billdenney** [comment]
No intentional gaslighting here.  😄 

Yes, I saw that there was faceting.  The request was for more control.  It wasn't initially clear to me that I could select multiple parameters in the column selection pull-down (that's on me).

And, I was generating some PK plots that had multiple analytes.  The analytes had very different maximum concentrations, so having access to `"free_y"` was the option I was looking for.

And, when I generated the plots, the number of plots looked like either a 4x3 or 4x4 matrix of panels (i.e. the `nrow` and `ncol` parameters to the facet commands).  I only had 3 panels that were generated, so the panels were small.  It looks like the number of panels is controlled by a configuration parameter (based on looking at the code you pointed to).  But in my case, it wasn't clear how to change that (because I didn't look; you may notice a theme here-- I was moving quickly) so having a way to override the default number of rows and columns would also help.  Maybe something like selections for "number of panel rows" and "number of panel columns" where each defaults to something like "default" (the current behavior) and can be modified to "tight" which would be the ceiling of the square root of the number of unique panels (not necessarily the best choice of words for it), or manually provided integers.

**Comment by john-harrold** [comment]
Sorry I was giving you a hard time :).

I can definitely add the scales to the facet element. 

The number of rows and columns is controlled in the yaml file for the FG module.  That's here:

https://github.com/john-harrold/formods/blob/1ca2415593ff683894508482ff0203014f65173c/inst/templates/FG.yaml#L188

Currently it's fixed at 3x4. My thoughts on this would be to have a section in the configuration file that  contains different dimensions. 2x1, 1x2, 4x4, etc. Then I can create a pull down for those dimensions. We can create some defaults that would cover most folks needs, but it would be configurable at the site level if someone wanted to add or remove options.

**Comment by billdenney** [comment]
😄

Is there a reason to fix the faceting rows and columns rather than letting the user define it?

**Comment by john-harrold** [comment]
Something like this. I need to add a label but the pulldown under the figure is the page number. 

<img width="809" alt="image" src="https://github.com/user-attachments/assets/a63c4278-59e3-4f96-b4ac-2589b6988eb0">

**Comment by billdenney** [comment]
That's exactly what I was thinking of!  Thanks!

**Comment by john-harrold** [comment]
It'll be in the next version of formods. If you want to try it out you'll need to install it off github. More ideas are welcome.
