### ISSUE TITLE
Feature request: Associate units with the columns of the data

### ISSUE THREAD

**Issue by billdenney** [john-harrold/ruminate#7]
This is not supported by PKNCA (yet?), but adding the units to your original data could be helpful.  It may also be possible to auto-detect the units from the same column name ending with "U" (like "AVAL" and "AVALU").

**Comment by john-harrold** [comment]
I'm not sure how this would work. Would it just be the units of concentration and your dosing units? Or would you have say: time, dose, concentration and amount units separated by commas? or would you have a separate column for each unit type (one for time, one for dose, one for concentration and one for amount)

**Comment by billdenney** [comment]
I was thinking of what you have added in #11.  These two issues are duplicates.
